/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongodb;

import java.util.ArrayList;
import java.util.List;

import builder.CentralProcessingUnit;
import builder.Chipset;
import builder.Color;
import builder.Computer;
import builder.ComputerBuilder;
import builder.DDRType;
import builder.MemoryModule;
import builder.Mouse;

public class App {

    public static void main(String[] args) {
        
        
        Mouse mouse = new Mouse(false, false, 0, Color.Red);
        CentralProcessingUnit cpu = new CentralProcessingUnit(3.2f, Chipset.Intel, true, 8);
        MemoryModule ram1 = new MemoryModule(3200f, 4, DDRType.DDR4);
        MemoryModule ram2 = new MemoryModule(3600f, 8, DDRType.DDR4);
        List<MemoryModule> ram = new ArrayList<MemoryModule>();
        ram.add(ram2);
        ram.add(ram1);
        Computer computer = new Computer(mouse, cpu, ram);
        


        ComputerBuilder computer1 = new ComputerBuilder();
        computer1
            .setMouse()
                .setWired(true)
                .setRgb(true)
                .setWirelength(3.2f)
                .setColor(Color.Red);
        
        computer1
            .setCentralProcessingUnit()
                .setChipset(Chipset.Intel)
                .setCoreCount(8)
                .setFrequency(3.2f)
                .setHyperthreading(false);
        
        computer1
            .addMemoryModule()
            .setMemory(4)
            .setDdrType(DDRType.DDR4)
            .setFrequency(3200f);
        computer1
            .addMemoryModule()
            .setMemory(8)
            .setDdrType(DDRType.DDR4)
            .setFrequency(3600f);
        
        
            
        ComputerBuilder computer2 = new ComputerBuilder();
        computer2
            .setMouse()
                .setWired(true)
                .setRgb(true)
                .setWirelength(3.2f)
                .setColor(Color.Red)
                .and()
            .setCentralProcessingUnit()
                .setChipset(Chipset.Intel)
                .setCoreCount(8)
                .setFrequency(3.2f)
                .setHyperthreading(false)
                .and()
            .addMemoryModule()
                .setMemory(4)
                .setDdrType(DDRType.DDR4)
                .setFrequency(3200f)
                .and()
            .addMemoryModule()
                .setMemory(8)
                .setDdrType(DDRType.DDR4)
                .setFrequency(3600f);
        
    }
}